### ISSUE TITLE
cupy.cuda.curand.CURANDError: CURAND_STATUS_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by xfyin1994** [hiroharu-kato/mesh_reconstruction#5]
**Hi, When I run the reconstruct.py,it show me this,I changed the `GPU=0` to try some other gpus,it still doesn't work and show me that.**

`Traceback (most recent call last):
  File "mesh_reconstruction/reconstruct.py", line 81, in <module>
    run()
  File "mesh_reconstruction/reconstruct.py", line 49, in run
    cp.random.seed(args.seed)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/generator.py", line 1113, in seed
    get_random_state().seed(seed)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/generator.py", line 1147, in get_random_state
    rs = RandomState(seed)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/generator.py", line 51, in __init__
    self._generator = curand.createGenerator(method)
  File "cupy/cuda/curand.pyx", line 90, in cupy.cuda.curand.createGenerator
  File "cupy/cuda/curand.pyx", line 94, in cupy.cuda.curand.createGenerator
  File "cupy/cuda/curand.pyx", line 83, in cupy.cuda.curand.check_status
cupy.cuda.curand.CURANDError: CURAND_STATUS_INITIALIZATION_FAILED`

**I have a try to comment `cp.random.seed(args.seed)`，and  it show me another infomation:
(I changed the code : `GPU=2` in line 14 and `#cp.random.seed(args.seed)`)**

`Traceback (most recent call last):
  File "mesh_reconstruction/reconstruct.py", line 81, in <module>
    run()
  File "mesh_reconstruction/reconstruct.py", line 61, in run
    model.to_gpu()
  File "/mnt/mesh_reconstruction-master/mesh_reconstruction/models.py", line 112, in to_gpu
    super(Model, self).to_gpu()
  File "/usr/local/lib/python2.7/dist-packages/chainer/device_resident.py", line 104, in to_gpu
    self.__to_device(visitor)
  File "/usr/local/lib/python2.7/dist-packages/chainer/device_resident.py", line 149, in __to_device
    self.device_resident_accept(to_device_visitor)
  File "/usr/local/lib/python2.7/dist-packages/chainer/link.py", line 961, in device_resident_accept
    d[name].device_resident_accept(visitor)
  File "/usr/local/lib/python2.7/dist-packages/chainer/link.py", line 958, in device_resident_accept
    super(Chain, self).device_resident_accept(visitor)
  File "/usr/local/lib/python2.7/dist-packages/chainer/link.py", line 447, in device_resident_accept
    super(Link, self).device_resident_accept(visitor)
  File "/usr/local/lib/python2.7/dist-packages/chainer/device_resident.py", line 38, in device_resident_accept
    visitor.visit_device_resident(self)
  File "/usr/local/lib/python2.7/dist-packages/chainer/device_resident.py", line 269, in visit_device_resident
    to_method(**kwargs)
TypeError: to_gpu() got an unexpected keyword argument 'device'`

**Comment by lzq2369** [comment]
(luFF) luzhiqing@o:~/luzhiqing_space/3D/mesh_reconstruction$ python mesh_reconstruction/reconstruct.py -d ./data/models -eid singleclass_02691156 -i ./data/examples/airplane_in.png -oi ./data/examples/airplane_out.png -oo ./data/examples/airplane_out.obj
Traceback (most recent call last):
  File "mesh_reconstruction/reconstruct.py", line 81, in <module>
    run()
  File "mesh_reconstruction/reconstruct.py", line 49, in run
    cp.random.seed(args.seed)
  File "/home/cvpruser/zsf/luzhiqing/luFF/lib/python3.7/site-packages/cupy/random/generator.py", line 1155, in seed
    get_random_state().seed(seed)
  File "/home/cvpruser/zsf/luzhiqing/luFF/lib/python3.7/site-packages/cupy/random/generator.py", line 1189, in get_random_state
    rs = RandomState(seed)
  File "/home/cvpruser/zsf/luzhiqing/luFF/lib/python3.7/site-packages/cupy/random/generator.py", line 51, in __init__
    self._generator = curand.createGenerator(method)
  File "cupy/cuda/curand.pyx", line 90, in cupy.cuda.curand.createGenerator
  File "cupy/cuda/curand.pyx", line 94, in cupy.cuda.curand.createGenerator
  File "cupy/cuda/curand.pyx", line 83, in cupy.cuda.curand.check_status
cupy.cuda.curand.CURANDError: CURAND_STATUS_INITIALIZATION_FAILED


How can I do ?

**Comment by bharadwajdhornala** [comment]
Hi @xfyin1994  I get the same error as yours. I am using Tensorflow=1.10.0 and pytorch=1.4.0. How did you solve it?
C:\Users\dhornala.bharadwaj\Documents\mesh_reconstruction-master\mesh_reconstruction-master>python mesh_reconstruction/reconstruct.py -d ./data/models -eid singleclass_02691156 -i ./data/examples/airplane_in.png -oi ./data/examples/airplane_out1.png -oo ./data/examples/airplane_out1.obj
Traceback (most recent call last):
  File "mesh_reconstruction/reconstruct.py", line 81, in <module>
    run()
  File "mesh_reconstruction/reconstruct.py", line 61, in run
    model.to_gpu()
  File "C:\Users\dhornala.bharadwaj\Documents\mesh_reconstruction-master\mesh_reconstruction-master\mesh_reconstruction\models.py", line 112, in to_gpu
    super(Model, self).to_gpu()
  File "c:\users\dhornala.bharadwaj\appdata\local\continuum\anaconda3\envs\disn\lib\site-packages\chainer\device_resident.py", line 125, in to_gpu
    self.__to_device(visitor)
  File "c:\users\dhornala.bharadwaj\appdata\local\continuum\anaconda3\envs\disn\lib\site-packages\chainer\device_resident.py", line 175, in __to_device
    self.device_resident_accept(to_device_visitor)
  File "c:\users\dhornala.bharadwaj\appdata\local\continuum\anaconda3\envs\disn\lib\site-packages\chainer\link.py", line 953, in device_resident_accept
    d[name].device_resident_accept(visitor)
  File "c:\users\dhornala.bharadwaj\appdata\local\continuum\anaconda3\envs\disn\lib\site-packages\chainer\link.py", line 950, in device_resident_accept
    super(Chain, self).device_resident_accept(visitor)
  File "c:\users\dhornala.bharadwaj\appdata\local\continuum\anaconda3\envs\disn\lib\site-packages\chainer\link.py", line 451, in device_resident_accept
    super(Link, self).device_resident_accept(visitor)
  File "c:\users\dhornala.bharadwaj\appdata\local\continuum\anaconda3\envs\disn\lib\site-packages\chainer\device_resident.py", line 50, in device_resident_accept
    visitor.visit_device_resident(self)
  File "c:\users\dhornala.bharadwaj\appdata\local\continuum\anaconda3\envs\disn\lib\site-packages\chainer\device_resident.py", line 305, in visit_device_resident
    to_method(**kwargs)
**TypeError: to_gpu() got an unexpected keyword argument 'device'**

**Comment by ujjawalcse** [comment]
Hey @bharadwajdhornala,
Did you find any solution for the error in `reconstruct.py  line 61, model.to_gpu()`
Please share if found any.

**Comment by Piplebobble** [comment]
hi @ujjawalcse 
have you find any solution for your error in model.to_gpu() or TypeError: to_gpu() got an unexpected keyword argument 'device'?
