### ISSUE TITLE
Error:a value of type "const float *" cannot be used to initialize an entity of type "float *"

### ISSUE THREAD

**Issue by sumai-1998** [hiroharu-kato/mesh_reconstruction#8]
~/mesh_reconstruction-master$ python mesh_reconstruction/train.py -eid singleclass_02691156 -cls 02691156 -ls 0.001 -li 1000 -ni 200000
Loading dataset: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.54s/it]
Loading dataset: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.88it/s]
iteration   main/loss_silhouettes  main/loss_smoothness  val/iou     elapsed_time
Exception in main training loop: /tmp/tmpbY1edp/bf28e852c345f19f0f38495ee3c20355_2.cubin.cu(19): error: a value of type "const float *" cannot be used to initialize an entity of type "float *"
this epoch [..................................................]  0.00%
1 error detected in the compilation of "/tmp/tmpbY1edp/bf28e852c345f19f0f38495ee3c20355_2.cubin.cu".
    7.3165 iters/sec. Estimated time to finish: 7:33:20.194782.
Traceback (most recent call last):
  File "/home/sm/.local/lib/python2.7/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/sm/mesh_reconstruction-master/mesh_reconstruction/training.py", line 37, in validation
    iou += model.evaluate_iou(*batch).sum()
  File "/home/sm/mesh_reconstruction-master/mesh_reconstruction/models.py", line 149, in evaluate_iou
    voxels_predicted = voxelization.voxelize(faces, 32, False)
  File "/home/sm/mesh_reconstruction-master/mesh_reconstruction/voxelization.py", line 175, in voxelize
    voxels0 = _voxelize_sub1(faces, size, 0)
  File "/home/sm/mesh_reconstruction-master/mesh_reconstruction/voxelization.py", line 64, in _voxelize_sub1
    )(cp.arange(bs * size * size).astype('int32'), faces, bs, nf, size, voxels)
  File "cupy/core/_kernel.pyx", line 572, in cupy.core._kernel.ElementwiseKernel.__call__
  File "cupy/core/_kernel.pyx", line 602, in cupy.core._kernel.ElementwiseKernel._get_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 402, in cupy.core._kernel._get_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 40, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 60, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 166, in cupy.core.core.compile_with_cache
  File "/home/sm/.conda/envs/NR1/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 166, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch, name + '.cu')
  File "/home/sm/.conda/envs/NR1/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 82, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/home/sm/.conda/envs/NR1/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 253, in compile
    raise CompileException(log, self.src, self.name, options)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "mesh_reconstruction/train.py", line 94, in <module>
    run()
  File "mesh_reconstruction/train.py", line 85, in run
    trainer.run()
  File "/home/sm/.local/lib/python2.7/site-packages/chainer/training/trainer.py", line 330, in run
    six.reraise(*sys.exc_info())
  File "/home/sm/.local/lib/python2.7/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/sm/mesh_reconstruction-master/mesh_reconstruction/training.py", line 37, in validation
    iou += model.evaluate_iou(*batch).sum()
  File "/home/sm/mesh_reconstruction-master/mesh_reconstruction/models.py", line 149, in evaluate_iou
    voxels_predicted = voxelization.voxelize(faces, 32, False)
  File "/home/sm/mesh_reconstruction-master/mesh_reconstruction/voxelization.py", line 175, in voxelize
    voxels0 = _voxelize_sub1(faces, size, 0)
  File "/home/sm/mesh_reconstruction-master/mesh_reconstruction/voxelization.py", line 64, in _voxelize_sub1
    )(cp.arange(bs * size * size).astype('int32'), faces, bs, nf, size, voxels)
  File "cupy/core/_kernel.pyx", line 572, in cupy.core._kernel.ElementwiseKernel.__call__
  File "cupy/core/_kernel.pyx", line 602, in cupy.core._kernel.ElementwiseKernel._get_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 402, in cupy.core._kernel._get_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 40, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 60, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 166, in cupy.core.core.compile_with_cache
  File "/home/sm/.conda/envs/NR1/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 166, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch, name + '.cu')
  File "/home/sm/.conda/envs/NR1/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 82, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/home/sm/.conda/envs/NR1/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 253, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: /tmp/tmpbY1edp/bf28e852c345f19f0f38495ee3c20355_2.cubin.cu(19): error: a value of type "const float *" cannot be used to initialize an entity of type "float *"

1 error detected in the compilation of "/tmp/tmpbY1edp/bf28e852c345f19f0f38495ee3c20355_2.cubin.cu".

**Comment by sumai-1998** [comment]
Package                       Version            
----------------------------- -------------------
backports.functools-lru-cache 1.6.4              
certifi                       2019.11.28         
chainer                       5.0.0              
cloudpickle                   1.3.0              
cupy                          6.7.0              
cycler                        0.10.0             
decorator                     4.4.2              
fastrlock                     0.4                
filelock                      3.0.12             
kiwisolver                    1.1.0              
matplotlib                    2.2.5              
networkx                      2.2                
neural-renderer               1.1.3              
numpy                         1.16.6             
Pillow                        6.2.2              
pip                           19.3.1             
protobuf                      3.17.3             
pyparsing                     2.4.7              
python-dateutil               2.8.1              
pytz                          2021.1             
PyWavelets                    1.0.3              
scikit-image                  0.14.5             
scipy                         1.2.3              
setuptools                    44.0.0.post20200106
six                           1.16.0             
subprocess32                  3.5.4              
tqdm                          4.61.1             
wheel                         0.36.2

**Comment by sumai-1998** [comment]
> Package Version
> 
> backports.functools-lru-cache 1.6.4
> certifi 2019.11.28
> chainer 5.0.0
> cloudpickle 1.3.0
> cupy 6.7.0
> cycler 0.10.0
> decorator 4.4.2
> fastrlock 0.4
> filelock 3.0.12
> kiwisolver 1.1.0
> matplotlib 2.2.5
> networkx 2.2
> neural-renderer 1.1.3
> numpy 1.16.6
> Pillow 6.2.2
> pip 19.3.1
> protobuf 3.17.3
> pyparsing 2.4.7
> python-dateutil 2.8.1
> pytz 2021.1
> PyWavelets 1.0.3
> scikit-image 0.14.5
> scipy 1.2.3
> setuptools 44.0.0.post20200106
> six 1.16.0
> subprocess32 3.5.4
> tqdm 4.61.1
> wheel 0.36.2

what's the right package version you guys can run

**Comment by sumai-1998** [comment]
line 25                 const float* face = &faces[(bn * nf + fn) * 9];
line 79             const float* face = &faces[(bn * nf + fn) * 9];

my gcc and g++ is 7.5    
maybe because this
